version: '3.7'

services:
  pubsub:
    image: google/cloud-sdk:latest
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085
    ports:
      - 8085:8085

  datastore:
    image: google/cloud-sdk:latest
    command: gcloud beta emulators datastore start --project=test --host-port=0.0.0.0:8081
    ports:
      - 8081:8081

  redis:
    image: redis:5.0
    ports:
      - 6379:6379
