name: Test
on: [push]

env:
  GO111MODULE: "on"

jobs:
  build:
    name: Build, Test
    runs-on: ubuntu-latest

    services:
      pubsub:
        image: knarz/pubsub-emulator
        ports:
          - 8085:8085

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go 1.16
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16
        id: go

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download Modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: go mod download

      - name: Test
        run: PUBSUB_EMULATOR_HOST=localhost:8085 go test -v -race -coverprofile=coverage.out ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.out
          fail_ci_if_error: true

